export const COUNTRIES = [
  { code: 'US', country: 'UnitedStates', area: 'American' },
  { code: 'GB', country: 'United Kingdom', area: 'British' },
  { code: 'CA', country: 'Canada', area: 'Canadian' },
  { code: 'CN', country: 'China', area: 'Chinese' },
  { code: 'HR', country: 'Croatia', area: 'Croatian' },
  { code: 'NL', country: 'Netherlands', area: 'Dutch' },
  { code: 'EG', country: 'Egypt', area: 'Egyptian' },
  { code: 'PH', country: 'Philippins', area: 'Filipino' },
  { code: 'FR', country: 'France', area: 'French' },
  { code: 'GR', country: 'Greece', area: 'Greek' },
  { code: 'IN', country: 'India', area: 'Indian' },
  { code: 'IE', country: 'Ireland', area: 'Irish' },
  { code: 'IT', country: 'Italy', area: 'Italian' },
  { code: 'JM', country: 'Jamaica', area: 'Jamaican' },
  { code: 'JP', country: 'Japan', area: 'Japanese' },
  { code: 'KE', country: 'Kenya', area: 'Kenyan' },
  { code: 'MY', country: 'Malaysia', area: 'Malaysian' },
  { code: 'MX', country: 'Mexico', area: 'Mexican' },
  { code: 'MA', country: 'Morocco', area: 'Moroccan' },
  { code: 'PL', country: 'Poland', area: 'Polish' },
  { code: 'PT', country: 'Portugal', area: 'Portuguese' },
  { code: 'RU', country: 'Russia', area: 'Russian' },
  { code: 'ES', country: 'Spain', area: 'Spanish' },
  { code: 'TH', country: 'Thailand', area: 'Thai' },
  { code: 'TN', country: 'Tunisia', area: 'Tunisian' },
  { code: 'TR', country: 'Turkey', area: 'Turkish' },
  { code: 'UA', country: 'Ukraine', area: 'Ukrainian' },
  { code: 'UY', country: 'Uruguay', area: 'Uruguayan' },
  { code: 'VN', country: 'Vietnam', area: 'Vietnamese' },
];
